version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: hhplus-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "hhplus-mysql"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redis-cluster

  # spring-app 서비스 부분
  spring-app:
    build: .
    image: hhplus-e-commerce:latest
    container_name: hhplus-e-commerce
    ports:
      - "8080:8080" # 이 줄을 추가
    depends_on:
      mysql:
        condition: service_healthy
      redis-7001:
        condition: service_started
    environment:
      SPRING_REDIS_CLUSTER_NODES: 172.20.0.2:7001,172.20.0.3:7002,172.20.0.4:7003,172.20.0.5:7004,172.20.0.6:7005,172.20.0.7:7006
    networks:
      - redis-cluster

  redis-7001:
    image: redis:latest
    container_name: redis-7001
    ports:
      - "7001:7001"
      - "17001:17001"
    command: >
      redis-server --port 7001
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.20.0.2
                   --cluster-announce-port 7001
                   --cluster-announce-bus-port 17001
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.2

  redis-7002:
    image: redis:latest
    container_name: redis-7002
    ports:
      - "7002:7002"
      - "17002:17002"
    command: >
      redis-server --port 7002
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.20.0.3
                   --cluster-announce-port 7002
                   --cluster-announce-bus-port 17002
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.3

  redis-7003:
    image: redis:latest
    container_name: redis-7003
    ports:
      - "7003:7003"
      - "17003:17003"
    command: >
      redis-server --port 7003
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.20.0.4
                   --cluster-announce-port 7003
                   --cluster-announce-bus-port 17003
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.4

  redis-7004:
    image: redis:latest
    container_name: redis-7004
    ports:
      - "7004:7004"
      - "17004:17004"
    command: >
      redis-server --port 7004
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.20.0.5
                   --cluster-announce-port 7004
                   --cluster-announce-bus-port 17004
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.5

  redis-7005:
    image: redis:latest
    container_name: redis-7005
    ports:
      - "7005:7005"
      - "17005:17005"
    command: >
      redis-server --port 7005
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.20.0.6
                   --cluster-announce-port 7005
                   --cluster-announce-bus-port 17005
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.6

  redis-7006:
    image: redis:latest
    container_name: redis-7006
    ports:
      - "7006:7006"
      - "17006:17006"
    command: >
      redis-server --port 7006
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.20.0.7
                   --cluster-announce-port 7006
                   --cluster-announce-bus-port 17006
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.7

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16