version: '3'

services:
  # =========================
  # MySQL
  # =========================
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redis-net

  # =========================
  # Spring App
  # =========================
  spring-app:
    build:
      context: . # 빌드 컨텍스트를 프로젝트 루트 디렉토리로 변경
      dockerfile: ./docker/spring-app/Dockerfile # Dockerfile의 경로를 명시
    image: hhplus-e-commerce
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis-master:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - redis-net

  # =========================
  # Redis Master
  # =========================
  redis-master:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - redis-net

  # =========================
  # Redis Replica
  # =========================
  redis-replica-1:
    image: redis:latest
    ports:
      - "6380:6380"
    command: redis-server --replicaof redis-master 6379
    links:
      - redis-master
    networks:
      - redis-net

  redis-replica-2:
    image: redis:latest
    ports:
      - "6381:6381"
    command: redis-server --replicaof redis-master 6379
    links:
      - redis-master
    networks:
      - redis-net

  # =========================
  # Redis Sentinels
  # =========================
  sentinel-1:
    build:
      context: ./docker/sentinel
      dockerfile: Dockerfile
    ports:
      - "26379:26379"
    env_file:
      - .env
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-net

  sentinel-2:
    build:
      context: ./docker/sentinel
      dockerfile: Dockerfile
    ports:
      - "26380:26379"
    env_file:
      - .env
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-net

  sentinel-3:
    build:
      context: ./docker/sentinel
      dockerfile: Dockerfile
    ports:
      - "26381:26379"
    env_file:
      - .env
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
