services:
  spring-app:
    cpus: "4.0"
    mem_limit: "4g"
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Xms512m -Xmx1536m
        -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "100"
      SPRING_KAFKA_PRODUCER_ACKS: "1"
      SPRING_KAFKA_PRODUCER_PROPERTIES_LINGER_MS: "10"
      SPRING_KAFKA_PRODUCER_PROPERTIES_BATCH_SIZE: "65536"

  mysql:
    cpus: "4.0"
    mem_limit: "4g"

  redis:
    cpus: "1.0"
    mem_limit: "1g"

  kafka:
    cpus: "2.0"
    mem_limit: "2g"
    environment:
      # 필요 시 파티션 수를 줄이고 싶다면 아래 주석 해제
      # KAFKA_CFG_NUM_PARTITIONS: "1"
      KAFKA_HEAP_OPTS: -Xms1g -Xmx2g

  connect:
    cpus: "1.0"
    mem_limit: "1g"
    environment:
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx1g"

  k6:
    cpus: "2.0"
    mem_limit: "2g"

  grafana:
    cpus: "0.5"
    mem_limit: "1g"

  influxdb:
    cpus: "2"
    mem_limit: "2g"