spring:
  application:
    name: hhplus

---
spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    url: jdbc:mysql://mysql:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.highlight_sql: true
  redis:
    sentinel:
      master: mymaster
      nodes:
        - sentinel-1:26379
        - sentinel-2:26379
        - sentinel-3:26379
  kafka:
    # ================================
    # Kafka 브로커 주소 (도커 네트워크 내부)
    # docker-compose.yml의 kafka 서비스 이름 + 포트
    # => kafka:9092 로 접근 가능
    # ================================
    bootstrap-servers: kafka:9092

redisson:
  config: |
    sentinelServersConfig:
      masterName: "mymaster"
      sentinelAddresses:
        - "redis://sentinel-1:26379"
        - "redis://sentinel-2:26379"
        - "redis://sentinel-3:26379"
      database: 0
  logging:
    level:
      org.springframework.boot: DEBUG