spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.highlight_sql: true

  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - localhost:26379
          - localhost:26380
          - localhost:26381

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://hhplus-mysql:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

---
spring.config.activate.on-profile: docker

spring:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - sentinel-1:26379
        - sentinel-2:26379
        - sentinel-3:26379

redisson:
  config: |
    sentinelServersConfig:
      masterName: "mymaster"
      sentinelAddresses:
        - "redis://sentinel-1:26379"
        - "redis://sentinel-2:26379"
        - "redis://sentinel-3:26379"
      database: 0